### ISSUE TITLE
You have no more of that ball left to use!

### ISSUE THREAD

**Issue by nirajmchauhan** [d-pollard/Pokemon-GO-node-api#3]
How do I get more pokeballs, is there a function which will go and get collect items from Pokestores ?

**Comment by d-pollard** [comment]
@nirajmchauhan - yes, depending on which file you are using, `poke.io.js` has a `GetFort` - and you can see an example in `exampleFort.js`.

Soon to be ported over to the `pokego.js` version too.

**Comment by d-pollard** [comment]
I'm going to close this for now
