### ISSUE TITLE
Error in exampleFort.js (Fix Included)

### ISSUE THREAD

**Issue by ButchMonkey** [d-pollard/Pokemon-GO-node-api#7]
There are 2 nested loops in exampleFort.js - 

```
...
for (var i = hb.cells.length - 1; i >= 0; i--) {
        // console.log(hb.cells[i])
        console.log(i)
        if(hb.cells[i].Fort) {
            var currentFortArr = hb.cells[i].Fort;
            for (var i = currentFortArr.length - 1; i >= 0; i--) {
                var currentFort = currentFortArr[i];
...
```

The outer for loop will only iterate once due to the reuse of "i" as a loop variable. Please change this to something else to fix. Thanks :)

Example.

```
...
for (var i = hb.cells.length - 1; i >= 0; i--) {
        // console.log(hb.cells[i])
        console.log(i)
        if(hb.cells[i].Fort) {
            var currentFortArr = hb.cells[i].Fort;
            for (var j = currentFortArr.length - 1; j >= 0; j--) {
                    var currentFort = currentFortArr[j];
...
```

**Comment by ButchMonkey** [comment]
Also, there is no handle for an undefined response in getFort()

**Comment by d-pollard** [comment]
Good catch, Ill check it out and change it! Unless you'd like to make a pull request

**Comment by ButchMonkey** [comment]
I'll let you patch it :)
Might do a pull request once I finish upgrading my copy of the fort scanning

**Comment by d-pollard** [comment]
Sweet! Looking forward to it

**Comment by d-pollard** [comment]
I pushed a fix out for it - thanks for the catch!
