### ISSUE TITLE
Getting stuck after received access token

### ISSUE THREAD

**Issue by ButchMonkey** [d-pollard/Pokemon-GO-node-api#9]
Running any of the examples to test with, using either PTC or Google get stuck after receiving the access token -

```
[i] Logging with user: *********
[i] Session token: *************************
[i] Received PTC access token! {Expires: 10800}
```

The script then hangs here with no further progress.

I appreciate that the unknown6 patch is still new.
Thanks

**Comment by ButchMonkey** [comment]
Update on this. 
After quite a while, the script ran. 

Further debugging this appears to be the GetApiEndpoint (api_req) function

**Comment by d-pollard** [comment]
Is this still an issue? I accept your PR, if it is, I can take a looksee at it - the Pokego.js file is going to need the unknown6 auth put in when I get a chance.

**Comment by ButchMonkey** [comment]
I think the issue is because I'm running on a cloud 9  virtual machine and Niantic probably IP blanket banned them.

I tried to add the device info and unknown6 into both files but no success, hence not adding it into the PR
